all::
	${MAKE} -C tests

tarprep::
	${MAKE} -C src $@
	${MAKE} -C include $@

clean::
	${MAKE} -C tests $@
	${MAKE} -C src $@

distclean::
	${MAKE} -C tests $@
	${MAKE} -C src $@
	${MAKE} -C include $@
