all::
	${MAKE} -C mcweatherd
	${MAKE} -C mcweather

tarprep::
	${MAKE} -C mcweatherd $@
	${MAKE} -C mcweather $@

clean::
	${MAKE} -C mcweatherd $@
	${MAKE} -C mcweather $@

distclean::
	${MAKE} -C mcweatherd $@
	${MAKE} -C mcweather $@
