#!/bin/sh

case "$1" in
  remove)
    # Before the package is removed.
    systemctl stop mcweatherd
    ;;
  upgrade)
    case "$0" in
      old-prerm)
        # old-prerm upgrade new-version
        #   Before an upgrade.
	systemctl stop mcweatherd
        ;;
      new-prerem)
        # new-prerm failed-upgrade old-version new-version
        #   If the above upgrade fails.
	;;
    esac
    ;;
  deconfigure)
    # deconfigure in-favour new-package new-version
       # [ removing old-package old-version ]
       #    Before package is deconfigured while dependency is replaced due to
       #    conflict.
       systemctl stop mcweatherd
    ;;
  remove)
    # remove in-favour new-package new-version
    #       Before the package is replaced due to conflict.
    ;;
esac